--- 
after_script: "set +e"
before_cache: 
  - "chmod -R a+r $HOME/.cargo"
before_deploy: 
  - "sh ci/before_deploy.sh"
before_install: 
  - "set -e"
  - "rustup self update"
branches: 
  only: 
    - /^v\d+\.\d+\.\d+.*$/
    - master
cache: cargo
deploy: 
  api_key: 
    secure: JAWZDa7izxqh/013aqxwSxhu4wndJfvQWngA/DMutC5J5ZTUEmA0UJG+VGCVcMVZOBu/IUy6tRmz3IgEqgW74FLc4UuBRH3RdInp+dpjUc2yTuUltOuT+skn5LGQXi+m8VeIxRS0PXCsN5twpOfSi0uuKu+UzMN9ZOX9wEy1svRlAUJdcT37LfvlS/lnxHoF+WuakZfFsP0QCrgI7uBY83X+wT6YAixiywzadKMqXDSNlJ7m0t9pJ1FsR0BgnoYiTI/L/3P3FDJCDzShujlU9P3xLvirV4/HB9NPG+IhuhTSCpBE8UIzCourAi6AgG3wdQGiR9S9QdwEuF3Y5Ya5l2tkJpqrk8FkBMVkH57m9iGV0j4mHDOvaRzMiPyYeuTTPKgbSWAvLOGouVRDP0SrZGjjcCvKSN4LVgO83uLjsg2XtdFoA89s/pNLsY2e07trT6jVm12P9uKdLWqkHdLJdGG4448aL8cIXntlCIHujpSmSikGtlGZZB6cvfkZQn/ZLhBxiGyk8n2V5hpqFml/tk6QDxyY04gSd1t/9aebOZmAGFYP0aufJpQe1GW13PQSdIQL6MZPtsk88OgP6EqUOSBCIAWuBd0cLds1SE+TELPyAPHWx5Z/y+mUEx4NoxRWWzNbQxOaMfXtLhE+xp7gdJYH7QtldagYz79UX/8wYbo=
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  file_glob: true
  provider: releases
  skip_cleanup: true
  true: 
    condition: "$TRAVIS_RUST_VERSION = stable"
    tags: true
dist: trusty
env: 
  global: 
    - CRATE_NAME=tokei
    - MAKE_DEB=yes
    - "DEB_MAINTAINER=\"Aaron Power <theaaronepower@gmail.com>\""
    - "DEB_DESCRIPTION=\"A utility that allows you to count code, quickly.\""
install: 
  - "sh ci/install.sh"
  - "source ~/.cargo/env || true"
language: rust
matrix: 
  allow_failures: 
    - 
      rust: nightly
  include: 
    - 
      env: TARGET=aarch64-unknown-linux-gnu
    - 
      env: TARGET=arm-unknown-linux-gnueabi
    - 
      env: TARGET=armv7-unknown-linux-gnueabihf
    - 
      env: TARGET=i686-unknown-linux-gnu
    - 
      env: TARGET=i686-unknown-linux-musl
    - 
      env: TARGET=mips-unknown-linux-gnu
    - 
      env: TARGET=mips64-unknown-linux-gnuabi64
    - 
      env: TARGET=mips64el-unknown-linux-gnuabi64
    - 
      env: TARGET=mipsel-unknown-linux-gnu
    - 
      env: TARGET=powerpc-unknown-linux-gnu
    - 
      env: TARGET=powerpc64-unknown-linux-gnu
    - 
      env: TARGET=powerpc64le-unknown-linux-gnu
    - 
      env: "TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1"
    - 
      env: TARGET=x86_64-unknown-linux-gnu
    - 
      env: TARGET=x86_64-unknown-linux-musl
    - 
      env: TARGET=i686-apple-darwin
      os: osx
    - 
      env: TARGET=x86_64-apple-darwin
      os: osx
    - 
      env: TARGET=i686-pc-windows-msvc
    - 
      env: TARGET=ix86_64-pc-windows-msvc
    - 
      env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - 
      env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly
notifications: 
  email: 
    on_success: never
script: 
  - "bash ci/script.sh"
services: docker
sudo: required
